Limit and length validations for length, breath, height, number and q…
odisha-muktasoft/MUKTA_IMPL pull request #677
Opened 2024-09-25 09:43 UTC by Kamalesh-egov

…uantity fields in measurement

2024-09-25 09:45 UTC, Tulika-eGov commented on frontend/micro-ui/web/micro-ui-internals/packages/modules/Measurement/src/components/MeasureCard.js
> +var multiply = function(num1, num2) {
@Kamalesh-egov please remove the methods which are not getting used

2024-09-25 10:22 UTC, Kamalesh-egov commented on frontend/micro-ui/web/micro-ui-internals/packages/modules/Measurement/src/components/MeasureCard.js
> +var multiply = function(num1, num2) {
I am using that

2024-09-25 10:26 UTC, Tulika-eGov requested changes

2024-09-25 10:26 UTC, Tulika-eGov commented on frontend/micro-ui/web/micro-ui-internals/packages/modules/Measurement/src/components/MeasureCard.js
> +var multiply = function(num1, num2) {
okay then move this to util file and then take import and call

2024-09-25 12:01 UTC, Tulika-eGov approved these changes

2024-09-27 04:58 UTC, Tulika-eGov approved these changes

2024-09-27 04:58 UTC, merged